site_name: Public Net tech
site_author: lewis
repo_url: https://github.com/lewisNFF/PublicNetTech
nav:
    - Home: index.md
    - how_to_use_mkdocs: use_mkdocs.md
    - blog component: blog_contain.md
    - sshfs: sshfs.md
theme: readthedocs